version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "16274:3306"
    environment:
      MYSQL_DATABASE: inventariodb
      MYSQL_USER: walter
      MYSQL_PASSWORD: YG6btOer
      MYSQL_ROOT_PASSWORD: YG6btOer
